# Библиотека NumPy


**NumPy (Numerical Python)** — библиотека для работы с числовыми массивами и математическими вычислениями. Это фундамент почти всего научного Python: pandas, matplotlib, scikit-learn и другие библиотеки построены на NumPy.

Содержание:
1. Установка и импорт
2. Создание массивов
3. Типы данных и атрибуты массива
4. Индексация и срезы
5. Форма массива: reshape, flatten, ravel
6. Векторизация: арифметика без циклов
7. Broadcasting (трансляция)
8. Агрегирующие функции
9. Случайные числа
10. Матричные операции и линейная алгебра
11. Сравнения, маски и булевы индексы
12. Полезные приёмы: where, concatenate, unique
13. Практические примеры


## 1. Установка и импорт

Если NumPy не установлен:

```
pip install numpy
```

Принято импортировать NumPy с коротким алиасом `np`.


In [1]:
!pip install numpy

In [2]:
import numpy as np

# Проверим версию
print(np.__version__)


2.1.3


## 2. Создание массивов

Главный объект NumPy — `ndarray` (n-dimensional array, многомерный массив).

Массив создаётся из списка функцией `np.array()`. В отличие от списка Python, массив хранит элементы **одного типа** и работает с ними гораздо быстрее.


In [3]:
# Массив из списка
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

# Из списка списков — двумерный массив (матрица)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [4]:
# Специальные массивы
print("np.zeros((2, 3)):", np.zeros((2, 3)))       # массив из нулей
print("np.ones((2, 3)):", np.ones((2, 3)))         # массив из единиц
print("np.full((2, 3), 7):", np.full((2, 3), 7))  # заполненный числом
print("np.eye(3):", np.eye(3))                     # единичная матрица


np.zeros((2, 3)): [[0. 0. 0.]
 [0. 0. 0.]]
np.ones((2, 3)): [[1. 1. 1.]
 [1. 1. 1.]]
np.full((2, 3), 7): [[7 7 7]
 [7 7 7]]
np.eye(3): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Последовательности чисел
print(np.arange(0, 10, 2))        # как range: от 0 до 9 с шагом 2
print(np.arange(5))               # от 0 до 4
print(np.linspace(0, 1, 5))       # 5 равномерно распределённых чисел от 0 до 1


[0 2 4 6 8]
[0 1 2 3 4]
[0.   0.25 0.5  0.75 1.  ]


## 3. Типы данных и атрибуты массива

| Атрибут | Что возвращает |
|---------|----------------|
| `arr.ndim` | число измерений (осей) |
| `arr.shape` | форма (кортеж размеров по каждой оси) |
| `arr.size` | общее число элементов |
| `arr.dtype` | тип данных элементов |


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("ndim (число осей):", arr.ndim)
print("shape (форма):   ", arr.shape)   # 2 строки, 3 столбца
print("size (элементов):", arr.size)
print("dtype (тип):     ", arr.dtype)


ndim (число осей): 2
shape (форма):    (2, 3)
size (элементов): 6
dtype (тип):      int64


In [8]:
# Массив всегда хранит элементы ОДНОГО типа
mixed = np.array([1, 2, 3.0, 4])   # int превратятся в float!
print(mixed, mixed.dtype)

# Можно указать тип явно
ints = np.array([1, 2, 3], dtype=np.int64)
floats = np.array([1, 2, 3], dtype=np.float64)
print(ints.dtype, floats.dtype)


[1. 2. 3. 4.] float64
int64 float64


## 4. Индексация и срезы

Работают почти как у списков Python, но срез массива — это **представление (view)** исходного массива, а не копия! Изменение среза изменит исходный массив. Для копии используйте `.copy()`.


In [13]:
arr = np.arange(10)

print("arr:      ", arr)
print("arr[3]:   ", arr[3])       # элемент по индексу
print("arr[2:6]: ", arr[2:6])     # срез
print("arr[::2]: ", arr[::2])     # каждый второй
print("arr[::-1]:", arr[::-1])    # разворот


arr:       [0 1 2 3 4 5 6 7 8 9]
arr[3]:    3
arr[2:6]:  [2 3 4 5]
arr[::2]:  [0 2 4 6 8]
arr[::-1]: [9 8 7 6 5 4 3 2 1 0]


In [14]:
b = arr[::-1]
print(b)
b [4] = 2222222
print(arr)

[9 8 7 6 5 4 3 2 1 0]
[      0       1       2       3       4 2222222       6       7       8
       9]


In [20]:
# Индексация двумерных массивов: matrix[строка, столбец]
matrix = np.array([[1, 2, 3, 0], [4, 5, 6,0], [7, 8, 9,0], [1,1 ,1,1]])
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
print(matrix[0, 2])     # первая строка, третий столбец -> 3
print(matrix[1])        # вся вторая строка
print(matrix[:, 2])     # весь первый столбец
print(matrix[0:2, 1:])  # подматрица: строки 0-1, столбцы 1-2


3
[4 5 6 0]
[3 6 9 1]
[[2 3 0]
 [5 6 0]]


In [21]:
# ВНИМАНИЕ: срез — это view, а не копия!
arr = np.arange(5)
view = arr[1:4]
view[0] = 999

print("view:", view)
print("arr: ", arr)     # исходный массив тоже изменился!

# Копирование делается явно
arr = np.arange(5)
copy = arr[1:4].copy()
copy[0] = 999
print("arr после copy:", arr)   # не изменился


view: [999   2   3]
arr:  [  0 999   2   3   4]
arr после copy: [0 1 2 3 4]


## 5. Форма массива: reshape, flatten, ravel


In [22]:
# reshape — изменить форму (общее число элементов должно совпадать!)
arr = np.arange(12)
print(arr)
matrix = arr.reshape(3, 4)
print("Было:", arr.shape, "-> Стало:", matrix.shape)
print(matrix)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
Было: (12,) -> Стало: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
# -1 — "вычисли этот размер сам"
arr = np.arange(21)
print(arr.reshape(3, -1))   # NumPy сам поймёт, что нужно 4 столбца


[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [29]:
# flatten и ravel — развернуть многомерный массив в одномерный
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
b = matrix.flatten()
print("flatten():", b)
b [0] = 222222 # показывает, что flatten и ravel делает копию. Создает новый массив.
print("ravel(): ", matrix.ravel())
print("shape после:", matrix.shape)   # исходный массив не изменился


[[1 2 3]
 [4 5 6]]
flatten(): [222222      2      3      4      5      6]
ravel():  [1 2 3 4 5 6]
shape после: (2, 3)


## 6. Векторизация: арифметика без циклов

Главная суперсила NumPy: операции применяются ко **всему массиву** сразу — без циклов. Это и быстрее, и короче.


In [34]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)        # поэлементное сложение
print(a * b)        # поэлементное умножение
print(a ** 2)       # квадраты всех элементов
print(a + 100)      # операция со скаляром — применяется ко всем элементам
print(a % 3)


[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]
[101 102 103 104]
[1 2 0 1]


In [ ]:
# Сравнение: списки vs массивы
py_list = [1, 2, 3, 4]
np_arr = np.array([1, 2, 3, 4])

# print(py_list * 2)   # список просто продублируется: [1,2,3,4,1,2,3,4]
print(np_arr * 2)      # массив умножит элементы: [2 4 6 8]

# Со списками нужны циклы или comprehensions, с NumPy — одна операция
print([x * 2 for x in py_list])


## 7. Broadcasting (трансляция)

Broadcasting — механизм, который позволяет выполнять операции с массивами **разных форм**: меньший массив "растягивается" до формы большего.

| Операция | Результат |
|----------|-----------|
| `(3, 3) + (3,)` | `(3, 3)` — строка прибавляется к каждой строке |
| `(3, 3) + (3, 1)` | `(3, 3)` — столбец прибавляется к каждому столбцу |
| `(3, 3) + скаляр` | `(3, 3)` — скаляр прибавляется ко всем элементам |


In [36]:
# Broadcasting в действии
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix + 10)          # скаляр ко всем элементам
print(matrix + [100, 200, 300])   # строка к каждой строке


[[11 12 13]
 [14 15 16]
 [17 18 19]]


ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [42]:
# Практический пример: нормализация данных
data = np.array([[10, 200, 30],
                 [20, 300, 40],
                 [30, 100, 50]], dtype=float)
print("data", data)
means = data.mean(axis=0)       # среднее по каждому столбцу
normalized = data - means       # вычитаем среднее из каждого столбца
print("Средние:", means)
print("После нормализации:")
print(normalized)
means = data.mean(axis=1)
print(means)     # среднее по каждой стоке?

data [[ 10. 200.  30.]
 [ 20. 300.  40.]
 [ 30. 100.  50.]]
Средние: [ 20. 200.  40.]
После нормализации:
[[ -10.    0.  -10.]
 [   0.  100.    0.]
 [  10. -100.   10.]]
[ 80. 120.  60.]


## 8. Агрегирующие функции

Функции `sum`, `mean`, `min`, `max`, `std` и другие могут работать:
- по **всему массиву** (без параметра `axis`)
- по **строкам или столбцам** (с параметром `axis`)

Правило: `axis=0` — свёртка по строкам (итог по каждому столбцу), `axis=1` — по столбцам (итог по каждой строке).


In [43]:
grades = np.array([[5, 4, 3], [4, 5, 5], [3, 4, 4]])

print("Все оценки:", grades, sep="\n")
print("Общая сумма:  ", grades.sum())
print("Среднее:      ", grades.mean())
print("Максимум:     ", grades.max())
print("Минимум:      ", grades.min())
print("Станд. откл.: ", grades.std())


Все оценки:
[[5 4 3]
 [4 5 5]
 [3 4 4]]
Общая сумма:   37
Среднее:       4.111111111111111
Максимум:      5
Минимум:       3
Станд. откл.:  0.7370277311900888


In [44]:
# axis=0 — по каждому СТОЛБЦУ (итог сверху вниз)
# axis=1 — по каждой СТРОКЕ (итог слева направо)
grades = np.array([[5, 4, 3], [4, 5, 5], [3, 4, 4]])

print("Сумма по столбцам (axis=0):", grades.sum(axis=0))
print("Сумма по строкам  (axis=1):", grades.sum(axis=1))
print("Среднее по строкам (axis=1):", grades.mean(axis=1))


Сумма по столбцам (axis=0): [12 13 12]
Сумма по строкам  (axis=1): [12 14 11]
Среднее по строкам (axis=1): [4.         4.66666667 3.66666667]


## 9. Случайные числа

Модуль `np.random` для генерации случайных данных.


In [ ]:
# Случайные числа из разных распределений
print(np.random.rand(3, 3))          # равномерное [0, 1)
print(np.random.randint(1, 101, 5))  # 5 целых от 1 до 100
print(np.random.randn(5))            # нормальное распределение (среднее 0, отклонение 1)


In [ ]:
# Генератор с фиксированным seed — для воспроизводимости результатов
rng = np.random.default_rng(seed=42)
print(rng.integers(0, 100, 5))
print(rng.random(3))

# Тот же seed — те же числа
rng2 = np.random.default_rng(seed=42)
print(rng2.integers(0, 100, 5))


## 10. Матричные операции и линейная алгебра


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A * B (поэлементно):")
print(A * B)
print("A @ B (матричное умножение):")
print(A @ B)      # или np.dot(A, B)
print("Транспонирование A.T:")
print(A.T)
print("Детерминант:   ", round(np.linalg.det(A), 2))
print("Обратная матрица:")
print(np.linalg.inv(A))


In [ ]:
# Решение системы линейных уравнений: 2x + y = 8, x + 3y = 9
coeffs = np.array([[2, 1], [1, 3]])
values = np.array([8, 9])

solution = np.linalg.solve(coeffs, values)
print("x =", solution[0], ", y =", solution[1])


## 11. Сравнения, маски и булевы индексы

Сравнение массивов возвращает **булеву маску**, которую можно использовать для фильтрации элементов.


In [ ]:
arr = np.arange(10)

mask = arr > 5
print("Маска:", mask)
print("Элементы > 5:", arr[mask])       # фильтрация по маске
print("Короткая запись:", arr[arr % 2 == 0])   # только чётные


In [ ]:
# Несколько условий через & и | (обязательно в скобках!)
arr = np.arange(20)
result = arr[(arr > 5) & (arr < 15)]
print(result)


In [ ]:
# Подсчёт и проверки по условию
arr = np.array([3, 8, 1, 9, 4, 7])

print("Сколько > 5:   ", np.sum(arr > 5))
print("Есть ли > 8:   ", np.any(arr > 8))
print("Все ли > 0:    ", np.all(arr > 0))
print("Индекс максимума:", np.argmax(arr))


## 12. Полезные приёмы: where, concatenate, unique


In [ ]:
# np.where — выбор значений по условию
arr = np.array([1, -2, 3, -4, 5])
result = np.where(arr > 0, arr, 0)   # положительные оставить, остальные -> 0
print(result)


In [ ]:
# Объединение и разделение массивов
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate([a, b]))
print(np.vstack([a, b]))    # стек по вертикали
print(np.hstack([a, b]))    # стек по горизонтали


In [ ]:
# Уникальные элементы и подсчёт
arr = np.array([1, 2, 2, 3, 3, 3, 4])
values, counts = np.unique(arr, return_counts=True)
print("Уникальные:", values)
print("Сколько раз:", counts)


## 13. Практические примеры


In [ ]:
# Задача: нормализация данных к диапазону [0, 1]
data = np.array([12, 45, 7, 89, 34, 56], dtype=float)
normalized = (data - data.min()) / (data.max() - data.min())
print("Исходные данные:", data)
print("Нормализованные:  ", normalized)


In [ ]:
# Задача: статистика по месячным продажам (12 месяцев)
sales = np.random.default_rng(7).integers(100, 1000, 12)
months = ["Янв", "Фев", "Мар", "Апр", "Май", "Июн",
          "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"]

print("Продажи по месяцам:", dict(zip(months, sales)))
print("Среднемесячные: ", sales.mean().round(1))
print("Лучший месяц:   ", months[np.argmax(sales)], "-", sales.max())
print("Месяцев выше среднего:", np.sum(sales > sales.mean()))


In [ ]:
# Задача: матрица расстояний между точками на плоскости
points = np.array([[0, 0], [3, 4], [6, 8]], dtype=float)

# Расстояния между всеми парами точек
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
distances = np.sqrt((diff ** 2).sum(axis=2))
print("Матрица расстояний:")
print(distances.round(1))


In [ ]:
# Задача: фильтрация выбросов через среднее и стандартное отклонение
data = np.array([10, 12, 11, 13, 100, 12, 11, 9, 105, 10], dtype=float)
threshold = 2   # всё, что дальше 2-х стандартных отклонений — выброс

mean, std = data.mean(), data.std()
clean = data[np.abs(data - mean) <= threshold * std]
print("Исходные данные:", data)
print(f"Среднее: {mean:.1f}, отклонение: {std:.1f}")
print("Без выбросов:   ", clean)


In [ ]:
# Задача: почему NumPy быстрее чистого Python?
py_list = list(range(1_000_000))
np_arr = np.arange(1_000_000)

import time

start = time.time()
py_result = sum(x ** 2 for x in py_list)
py_time = time.time() - start

start = time.time()
np_result = np.sum(np_arr ** 2)
np_time = time.time() - start

print(f"Python-список: {py_time:.4f} сек")
print(f"NumPy-массив:  {np_time:.4f} сек")
print(f"NumPy быстрее в ~{py_time / np_time:.0f} раз")


## Итоги

| Задача | Инструмент NumPy |
|--------|------------------|
| Создать массив | `np.array`, `np.zeros`, `np.ones`, `np.arange`, `np.linspace` |
| Узнать форму | `arr.shape`, `arr.ndim`, `arr.size` |
| Изменить форму | `arr.reshape`, `arr.flatten` |
| Операции без циклов | векторизация: `arr * 2`, `a + b` |
| Массивы разных форм | broadcasting |
| Сумма, среднее и т.д. | `arr.sum()`, `arr.mean(axis=0)` |
| Случайные числа | `np.random.default_rng()` |
| Матрицы | `A @ B`, `A.T`, `np.linalg.solve` |
| Фильтрация | булевы маски: `arr[arr > 5]` |
| Условие с выбором | `np.where` |
| Объединение | `np.concatenate`, `np.vstack`, `np.hstack` |

**Попробуйте сами:** перепишите любой свой код со списками на NumPy — вы удивитесь, насколько он станет короче и быстрее!
